export const BARANGAY_LIST = [
  "Barangay 1",
  "Barangay 2",
  "Barangay 3",
  "Barangay 4",
  "Barangay 5",
  "Barangay 6",
  "Barangay 7",
  "Barangay 8",
  "Barangay 9",
  "Barangay 10",
  "Barangay 11",
  "Barangay 12",
  "Barangay 13",
  "Barangay 14",
  "Barangay 15",
  "Barangay 16",
  "Barangay 17",
  "Barangay 18",
  "Barangay 19",
  "Barangay 20",
  "Barangay 21",
  "Barangay 22",
  "Barangay 23",
  "Barangay 24",
  "Alangilan",
  "Balagtas",
  "Balete",
  "Banaba Center",
  "Banaba Kanluran",
  "Banaba Silangan",
  "Banaba Ibaba",
  "Bilogo",
  "Bolbok",
  "Bukal",
  "Calicanto",
  "Catandala",
  "Concepcion",
  "Conde Itaas",
  "Conde Labak",
  "Cuta",
  "Dalig",
  "Dela Paz",
  "Dela Paz Pulot Aplaya",
  "Dela Paz Pulot Itaas",
  "Domoclay",
  "Dumantay",
  "Gulod Itaas",
  "Gulod Labak",
  "Haligue Kanluran",
  "Haligue Silangan",
  "Ilihan",
  "Kumba",
  "Kumintang Ibaba",
  "Kumintang Ilaya",
  "Libjo",
  "Liponpon",
  "Maapas",
  "Mabacong",
  "Mahabang Dahilig",
  "Mahabang Parang",
  "Mahacot Kanluran",
  "Mahacot Silangan",
  "Malalim",
  "Malibayo",
  "Malitam",
  "Maruclap",
  "Pagkilatan",
  "Paharang Kanluran",
  "Paharang Silangan",
  "Pallocan Kanluran",
  "Pallocan Silangan",
  "Pinamucan Ibaba",
  "Pinamucan",
  "Pinamucan Silangan",
  "Sampaga",
  "San Agapito",
  "San Agustin Kanluran",
  "San Agustin Silangan",
  "San Andres",
  "San Antonio",
  "San Isidro",
  "San Jose Sico",
  "San Miguel",
  "San Pedro",
  "Santa Clara",
  "Santa Rita Aplaya",
  "Santa Rita Kalsada",
  "Santo Domingo",
  "Santo Niño",
  "Simlong",
  "Sirang Lupa",
  "Sorosoro Ibaba",
  "Sorosoro Ilaya",
  "Sorosoro Karsada",
  "Tabangao Aplaya",
  "Tabangao Ambulong",
  "Tabangao Dao",
  "Talahib Pandayan",
  "Talahib Payapa",
  "Talumpok Kanluran",
  "Talumpok Silangan",
  "Tingga Itaas",
  "Tingga Labak",
  "Tulo",
  "Wawa",
];